### ISSUE TITLE
option --page-results documented but doesn't work

### ISSUE THREAD

**Issue by jonassmedegaard** [perlancar/perl-App-RegexpPatternUtils#2]
Output of `show-regexp-pattern-module --help` includes this:
>   --page-result  {da_DK|en_US Filter output through a pager}

However, output of `show-regexp-pattern-module --page-results Example` is this:
> Unknown PerlIO layer "locale" at /home/jonas/perl5/lib/perl5/Perinci/CmdLine/Lite.pm line 427.
> show-regexp-pattern-module: ERROR 500: GetOptions failed

**Comment by perlancar** [comment]
This is caused by the same thing in #3 and has been fixed.

Note that the option name is `--page-result` and not `--page-results`.

**Comment by jonassmedegaard** [comment]
Thanks for the swift reaction.

Seems however that the issue was not solved: With Perinci-CmdLine-Lite-1.905 installed, `show-regexp-pattern-module --page-result Example` fails for me:
> Can't exec "Example": Ingen sådan fil eller filkatalog at /home/jonas/perl5/lib/perl5/Perinci/CmdLine/Base.pm line 1733.
> binmode() on closed filehandle $handle at /home/jonas/perl5/lib/perl5/Perinci/CmdLine/Lite.pm line 431.
> print() on closed filehandle $handle at /home/jonas/perl5/lib/perl5/Perinci/CmdLine/Base.pm line 1870.

**Comment by jonassmedegaard** [comment]
ah, never mind: `show-regexp-pattern-module --page-result --name=Example` works.

**Comment by perlancar** [comment]
Hm strange. `show-regexp-pattern-module Example --page` works here without any warning. I've tried setting LANG/LANGUAGE to non-English and it works too.

**Comment by jonassmedegaard** [comment]
For me, `show-regexp-pattern-module Example --page` works fine.
But `show-regexp-pattern-module --page Example` does not.

`show-regexp-pattern-module --help` seems to indicate that `Example` should be listed last (but the output of --help is generally too terse to be really useful: Requires guessing that "name" means the name of a pattern module).

**Comment by jonassmedegaard** [comment]
The option `--page` that you mention and I now succesfully tested seems undocumented.

**Comment by perlancar** [comment]
> The option `--page` that you mention and I now succesfully tested seems undocumented.

It's the `auto_abbrev` feature of Getopt::Long. You can use only a unique prefix of an option as long as it's unique. So `--page-result` can be written as `--page` (or `--pag`, or `--pa`).

**Comment by perlancar** [comment]
> For me, `show-regexp-pattern-module Example --page` works fine.
> But `show-regexp-pattern-module --page Example` does not.
> 
> `show-regexp-pattern-module --help` seems to indicate that `Example` should be listed last (but the output of --help is generally too terse to be really useful: Requires guessing that "name" means the name of a pattern module).

Ah, I see. `--page-result` takes an optional argument which is the pager program. So you can say:

    % show-regexp-pattern-module Example --page

to use the default pager, or:

    % show-regexp-pattern-module Example --page=more
    % show-regexp-pattern-module Example --page more

To pick a specific pager. That's why this doesn't work as `Example` will be interpreted as a pager program to use.

    % show-regexp-pattern-module --pager Example
    % show-regexp-pattern-module --pager=Example

**Comment by perlancar** [comment]
> the output of --help is generally too terse to be really useful: Requires guessing that "name" means the name of a pattern module).

I've added a summary for the `name` option. Hopefully it's clearer now.

**Comment by jonassmedegaard** [comment]
yes, `name` definition in `--help` output is clearer now. Thanks.

To avoid option/argument confusion, I suggest to add separator ` -- ` to `--help` output, like this:
```
Usage:
  show-regexp-pattern-module --help (or -h, -?)
  show-regexp-pattern-module --version (or -v)
  show-regexp-pattern-module [--format=name] [--json] [-l] [--list]
    [--(no)naked-res] [--page-result[=program]] [--view-result[=program]]
    -- [name]
```

**Comment by perlancar** [comment]
> To avoid option/argument confusion, I suggest to add separator -- to --help output, like this:

Fair enough, it's been added in Perinci::Sub::To::CLIDocData 0.295 and I'm testing how it looks in App::RegexpPatternUtils 0.006.

**Comment by jonassmedegaard** [comment]
Looks good to me. Thanks!
